#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom batchelor correctExperiments
#' @importFrom batchelor NoCorrectParam
#' @importFrom batchelor regressBatches
#' @importFrom bluster NNGraphParam
#' @importFrom circlize colorRamp2
#' @importFrom cluster agnes
#' @importFrom DBI dbConnect
#' @importFrom DBI dbDisconnect
#' @importFrom DBI dbReadTable
#' @importFrom DBI dbWriteTable
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr coalesce
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr one_of
#' @importFrom dplyr pull
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr summarize
#' @importFrom dplyr top_n
#' @importFrom EnsDb.Hsapiens.v86 EnsDb.Hsapiens.v86
#' @importFrom ensembldb transcripts
#' @importFrom fs dir_ls
#' @importFrom fs path
#' @importFrom fs path_abs
#' @importFrom fs path_dir
#' @importFrom fs path_expand
#' @importFrom fs path_ext_remove
#' @importFrom fs path_ext_set
#' @importFrom fs path_file
#' @importFrom glue glue
#' @importFrom methods is
#' @importFrom methods slot
#' @importFrom methods slot<-
#' @importFrom purrr flatten_chr
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_if
#' @importFrom purrr map_int
#' @importFrom purrr map_lgl
#' @importFrom purrr pmap
#' @importFrom purrr reduce
#' @importFrom RSQLite SQLite
#' @importFrom S4Vectors metadata
#' @importFrom scater runPCA
#' @importFrom scater runTSNE
#' @importFrom scater runUMAP
#' @importFrom scran clusterCells
#' @importFrom scran computeSumFactors
#' @importFrom scran cyclone
#' @importFrom scran findMarkers
#' @importFrom scran getTopHVGs
#' @importFrom scran modelGeneVar
#' @importFrom scran quickCluster
#' @importFrom scuttle addPerCellQCMetrics
#' @importFrom scuttle logNormCounts
#' @importFrom stringr str_detect
#' @importFrom stringr str_remove
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_to_title
#' @importFrom tibble column_to_rownames
#' @importFrom tibble enframe
#' @importFrom tibble rownames_to_column
#' @importFrom utils capture.output
#' @importFrom utils data
#' @importFrom utils head
#' @importFrom utils packageVersion
#' @importFrom utils read.csv
#' @importFrom utils sessionInfo
#' @importFrom megadepth bam_to_bigwig
## usethis namespace: end
#' @import SingleCellExperiment
NULL
